apiVersion: v1
kind: ConfigMap
metadata:
  name: my-service-configmap
  namespace: my-namespace
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      }
    }
